# Generated by Django 5.0.4 on 2024-05-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('has_backside', models.BooleanField(default=False)),
                ('OCRLabels', models.TextField(blank=True, null=True)),
                ('country', models.ManyToManyField(blank=True, related_name='country', to='accounts.country')),
            ],
        ),
    ]
