# Generated by Django 5.0.4 on 2024-05-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_documentset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentSet',
        ),
    ]
