# Generated by Django 5.0.4 on 2024-05-04 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_country', to='accounts.country'),
        ),
    ]
