# Generated by Django 5.0.4 on 2024-05-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country_name',
        ),
    ]
