# Generated by Django 5.0.4 on 2024-05-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_country', to='accounts.country'),
        ),
        migrations.CreateModel(
            name='DocumentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('has_backside', models.BooleanField(default=False)),
                ('OCRLabels', models.TextField(blank=True, null=True)),
                ('country_name', models.ManyToManyField(blank=True, related_name='country', to='accounts.country')),
            ],
        ),
    ]
