# Generated by Django 5.0.4 on 2024-05-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_country_name_documentset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentset',
            old_name='OCRLabels',
            new_name='ocr_labels',
        ),
    ]
