# Generated by Django 5.0.4 on 2024-05-05 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customerdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nationality', to='accounts.country'),
        ),
    ]
