# Generated by Django 5.0.4 on 2024-05-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customer_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='gender',
            new_name='sex',
        ),
    ]
